modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/LittleFrames/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="littleframes"
    logoFile="littleframes.png"
    version="1.3.7"
    displayName="LittleFrames"
    displayURL="https://modrinth.com/mod/littlepictureframes"
    authors="CreativeMD"
    description='''Adds ways to display images/videos/audio ingame.'''

[[dependencies.littleframes]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littleframes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littleframes]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.15"

[[dependencies.littleframes]]
   modId="watermedia"
   mandatory=true
   ordering="NONE"
   side="CLIENT"
   versionRange="[2.0,2.1)"

