modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/LittleFrames/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="littleframes"
    logoFile="littleframes.png"
    version="1.4.5"
    displayName="LittleFrames"
    displayURL="https://modrinth.com/mod/littlepictureframes"
    authors="CreativeMD"
    description='''Adds ways to display images/videos/audio ingame.'''

[[dependencies.littleframes]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littleframes]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.littleframes]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="2.13.0"

[[dependencies.littleframes]]
   modId="watermedia"
   type="required"
   ordering="NONE"
   side="CLIENT"
   versionRange="[2.1,2.2)"

